backend:
  name: github
  repo: hputzek/portfolio-rocio # Path to your Github repository
  branch: master # Branch to update

publish_mode: editorial_workflow
media_folder: "assets/images/uploads" # Media files will be stored in the repo under this path
public_folder: "/" # The src attribute for uploaded media will begin this path

collections: # A list of collections the CMS should be able to edit
  - name: "projects-collection" # all the things in one entry, for documentation and quick testing
    create: true # Allow users to create new documents in this collection
    label: "Projekte"
    files:
      - name: "projects"
        label: "Projekte"
        description: "Projekte, die im Slider angezeigt werden"
        file: "static/data/projekte.json"
        fields:
          - label: "Projekt"
            name: "project"
            widget: "list"
            fields:
              - label: "Seite"
                name: "slide"
                widget: "list"
                fields:
                  - {label: "Seitentitel", name: "title", widget: "string"}
                  - label: "Seiteninhalte"
                    name: "elements"
                    widget: "object"
                    fields:
                      - label: "Überschriften"
                        name: "headlines"
                        widget: "list"
                        fields:
                          - {label: "headline", name: "type", widget: "hidden", default: "hidden"}
                          - {label: "Überschrift", name: "content", widget: "string"}
                          - {label: "Abstand links in %", name: "positionLeftInPercent", widget: "number"}
                          - {label: "Abstand von oben in %", name: "positionTopInPercent", widget: "number"}
                          - {label: "z-index", name: "zIndex", widget: "number"}
